### PR TITLE
fix test suite

### PR DESCRIPTION
**Pull request by doudou**

### CODE REVIEW

**Comment by marvin2k** [comment]
I would choose `overwrite_existing_files` as name for the property.

Also: what are the steps to let this test actually run? Is the `minitest` compatible with ruby-1.9.1? Got errors from [orocos.rb/../component.rb](https://github.com/rock-core/tools-orocosrb/blob/master/lib/orocos/test/component.rb#L3), changing the line3 into `require 'minitest/autorun'` allows the test to runs but leads to errors like

```bash
ruby test/test_logger.rb
....
NoMethodError: undefined method `new_ruby_task_context' for #<TC_BasicBehaviour:0x000000022143a8>
    test/test_logger.rb:105:in `test_log_port'
...
```

**Comment by doudou** [comment]
Should have mentioned ... this depends on orogen_loaders. I should be able to finally merge the branches tomorrow or the day after tomorrow and will re-ping here. I'll also update the property name as suggested.

**Comment by goldhoorn** [comment]
Why instead of adding such a property (whis for me is only for testing) removing the file in the testsuite is the file was not cleaned up before?

It feels hacky to add a property only for the testsuite

**Comment by doudou** [comment]
> It feels hacky to add a property only for the testsuite

While I did add it for the test suite, I don't feel that it is *only* for the test suite.

**Comment by jakobs** [comment]
The property seems fine to me.

**Comment by goldhoorn** [comment]
@doudou: can you please rename the propery as marvin2k suggested, then ack for merge

**Comment by doudou** [comment]
Updated

**Comment by goldhoorn** [comment]
:+1:

**Pull request merged**
